### ISSUE TITLE
FR: Support for monorepos within subdirectory?

### ISSUE THREAD

**Issue by mikestopcontinues** [ranyitz/qnm#101]
I'm not usually in my monorepo root. It would be great if qnm looked for the nearest node_modules dir, even if it required a flag. Maybe `-n, --nearest`? This seems like a sensible solution as many monorepo setups have multiple node_modules directories, though most seem to be moving away from that.

Anyway, great tool! Thanks!

**Comment by mikestopcontinues** [comment]
The snag I'm hitting is that all my node_modules are hoisted, so when I'm within a package dir, qnm throws an error.

First thought: In the event of a package.json but no node_modules, offer a pretty error that explains the situation.

I'm not sure what the optimal logic should be otherwise, if this situation is handled at all. Given there's only a few monorepo formats out there, maybe the right call is an `-m, --monorepo` arg that looks upward for the telltale signs of a monorepo root?

Here's where things go wrong for me:

```
monorepo/
  package.json // {"workspaces": ["apps/*"]}
  node_modules/
  apps/
    editor/
      package.json // and no node_modules
```

I spend most of my time in /editor, but I want to introspect /monorepo.

**Comment by mikestopcontinues** [comment]
Hey @ranyitz, 

I'm very much in favor of `qnm` automatically inferring the context and just showing everything (with annotations). That's exactly what I'm looking for given the context. Even with hoisting, there's circumstances where you can end up with local `node_modules`, so I would definitely want to know if one popped up.

Regarding a different package versions, I think there's a few useful cases:
1. Your case, different root vs local, which implies the wrong package is being used or an incomplete upgrade. Definitely useful.
1. Different across the dependency tree for this local package, which suggests an opportunity to optimize. E.G. @mono/A -> (@mono/B, @npm/C@1), @mono/B -> (@npm/C@2)
1. Lastly, different across the entire monorepo root/local `node_modules`. Does `qnm` already do this? (Without local `node_modules` I can't easily tell.) You'd really only want to see it in root, but it'll expand the eagle-eye view `qnm` already offers.

Anyway, I hope I was able to offer some more context, and thanks again!

**Comment by ranyitz** [comment]
Thanks @mikestopcontinues 

In that case, let me suggest a solution.
What if we'll show the qnm output like you would run it from the root. The only difference is that we'll mark the current package in some way that would be clear to the user it's the current working directory.

What do you think?

**Comment by ranyitz** [comment]
@mikestopcontinues please try `v2.8.0` and let me know whether the fixes of #105 solve this issue. If not, feel free to re-open this issue.

**Comment by mikestopcontinues** [comment]
@ranyitz I think the PR will be a great solution. The only sticking point is that I'm still getting the `could not find node_modules directory` error while in a sub-package. No special localized view is totally ok, but I'd still like to be able to run `qnm` from where I'm working.

**Comment by ranyitz** [comment]
Yes, This case still needs to be addressed. Reopening

**Comment by ranyitz** [comment]
@mikestopcontinues Please check [2.9.0](https://github.com/ranyitz/qnm/blob/master/CHANGELOG.md#v290). It should support the use-case of an empty `node_modules` directory within a monorepo.

**Comment by mikestopcontinues** [comment]
Hey, something is still amiss.

<img width="294" alt="Screen Shot 2022-06-25 at 8 11 57 AM" src="https://user-images.githubusercontent.com/150434/175774927-845c259e-0627-4424-9d22-90e9ecec3d6e.png">

Here's my tree:
```
/repo
 - node_modules
 - package.json {"workspaces": ["libs/*"]}
 - /libs
   - /arc-model
     - package.json
```

What other info can I send your way?

**Comment by ranyitz** [comment]
@mikestopcontinues oh, I forgot to fix the fuzzy search mode. I'll push a fix soon.

**Comment by mikestopcontinues** [comment]
@ranyitz Thanks!

**Comment by ranyitz** [comment]
@mikestopcontinues This should be fixed on `v2.9.2` (https://github.com/ranyitz/qnm/pull/112)

**Comment by mikestopcontinues** [comment]
Nice! Works like a charm!

**Comment by ranyitz** [comment]
@mikestopcontinues thanks for you patience and help with this!
