### ISSUE TITLE
Better experience with npx

### ISSUE THREAD

**Issue by roymiloh** [ranyitz/qnm#27]
When I do, for instance, `npx qnm --why x` - there's a post-install script that installs smth (with `tabtab`). I've not checked why, but it's a bit frustrating to install it every time I use `npx` (and wait for `npm install` under the hood).

**Comment by ranyitz** [comment]
Thanks @roymiloh for reporting this, I've removed the post install script and added a custom command instead. https://github.com/ranyitz/qnm/blob/master/README.md#install-completions

Available from [0.13.2](https://github.com/ranyitz/qnm/blob/v0.13.2/CHANGELOG.md#0132-may-30-2018)
