### ISSUE TITLE
fuzzy search not working properly when deleting chars

### ISSUE THREAD

**Issue by miglrodri** [ranyitz/qnm#37]
Hello guys,

I recorded a gif with the problem.

I'm using windows 10, with the cmd.

I type lodash and all is great, but when i delete 1 char the app don't work properly.

https://i.imgur.com/GKqnhz9.gif

Best regards, Miguel

**Comment by ranyitz** [comment]
Hey @miglrodri 👋 Thanks for opening an issue!

I'm sorry it took some time to answer.
I've done a PR to add windows support, tested it on a windows 10 machine it looks great, I'll merge and release a new version soon.
