### ISSUE TITLE
Fail with proper exit codes

### ISSUE THREAD

**Issue by yardnsm** [ranyitz/qnm#8]
Currently, there are some cases when an error is thrown and the program terminates with a `0` exit code, whereas it should return a non-zero code: https://github.com/ranyitz/qnm/blob/master/src/printer.js#L50-L66.

We could utilize the [error handler](https://github.com/ranyitz/qnm/blob/master/src/handler-error.js) and simply `throw` exceptions in these cases. Also, we shouldn't exit the program while we run unit tests, since it would cause jest to fail.

Awesome work BTW 😄

**Comment by ranyitz** [comment]
Thanks @yardnsm! 😃 

You are absolutely right,
Please go over #10 And let me know if it solves it correctly.
